# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisatie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(db_index=True, max_length=150)),
            ],
            options={
                'verbose_name': 'organisatie',
                'ordering': ('naam',),
            },
        ),
        migrations.CreateModel(
            name='Werknemer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voornaam', models.CharField(max_length=150)),
                ('tussenvoegsel', models.CharField(blank=True, max_length=5)),
                ('achternaam', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('wachtwoord', models.CharField(blank=True, max_length=50)),
                ('nieuwwachtwoord', models.CharField(blank=True, max_length=50)),
                ('rol', models.CharField(default=None, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisatie', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='werknemers', to='creditoapp.Organisatie')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
